version: '3'
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
